
name: test-orders
on:
   pull_request:
      paths: 
      - 'auth/**'

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: test orders
      run: cd orders && npm install && npm run test:ci

